Trigger collection.item.removed after collection item has been remove…
VincentChalnot/SidusEAVBootstrapBundle pull request #2
Opened 2017-03-07 17:26 UTC by dom18fr

…d & collection update event trigged on collection wrapper

2017-03-08 20:11 UTC, VincentChalnot requested changes
Yo, je t'ai fait des retours sur ta PR

2017-03-08 20:11 UTC, VincentChalnot commented on Resources/public/js/bootstrap.collection.js
> +        $this.closest('[id^=sidus_tabbed_data_]').trigger('collection.item.added', list.find('li').last());
Tu peux pas te baser sur l'ID comme ça, il faut récupérer l'ID de la collection en utilisant le data-collection présent sur le lien. En fait t'as déjà la bonne collection dans la variable "collection" ;)

2017-03-08 20:11 UTC, VincentChalnot commented on Resources/public/js/bootstrap.collection.js
> +          selector = $this.attr('data-field')
what ?

2017-03-08 20:11 UTC, VincentChalnot commented on Resources/public/js/bootstrap.collection.js
> +        var $collection = $this.closest('[id^=sidus_tabbed_data_]');
Même remarque que plus haut, mais ça mériterait en plus de passer l'objet supprimé.
C'est quoi ce "$" en début de variable ? 😛

2017-03-08 20:11 UTC, VincentChalnot commented on Resources/public/js/bootstrap.collection.js
> -                data = $this.data('addfield')
Re-what ?

2017-03-08 20:11 UTC, VincentChalnot commented on Resources/public/js/bootstrap.collection.js
> -                data = $this.data('removefield')
Re-re-what ?

2017-03-08 22:22 UTC, dom18fr commented on Resources/public/js/bootstrap.collection.js
> +        $this.closest('[id^=sidus_tabbed_data_]').trigger('collection.item.added', list.find('li').last());
yep effectivement j'étais passé à côté du data-collection ET de la variable "collection" :)

2017-03-08 22:22 UTC, dom18fr commented on Resources/public/js/bootstrap.collection.js
> +        var $collection = $this.closest('[id^=sidus_tabbed_data_]');
Pour ce qui est de renvoyer l'objet, 2 questions : 
1. pourquoi ?
2. comment ?
Au moment ou on trigg l'evenement, l'élément est dejà supprimé, et c'est souhaitable, il faut pouvoir compter le nombre d'éléments restants par exemple.
A la limite, on pourrait trigger 2 events un "before.remove" et un "removed" pour couvrir tous les cas d'usage non ? ou alors j'ai pas compris un truc.

Alors le "$", ça ressemble a un fail de dev php fatigué mais il n'en est rien :) C'est une convention pour distinguer un objet jQuery d'un autre variable en js. Comme quand on écrit $this = $(this) finalement.

2017-03-08 22:25 UTC, dom18fr commented on Resources/public/js/bootstrap.collection.js
> -                data = $this.data('removefield')
cf justifications confuses sus-mentionnées.

2017-03-08 22:25 UTC, dom18fr commented on Resources/public/js/bootstrap.collection.js
> -                data = $this.data('addfield')
Re-chelou, phpstorm, config, tout ça

2017-03-09 08:18 UTC, VincentChalnot commented on Resources/public/js/bootstrap.collection.js
> +        var $collection = $this.closest('[id^=sidus_tabbed_data_]');
Ouais effectivement ça serait plus pertinent de passer l'élément sur un "before"...
Ok, on laisse comme ça.

2017-03-09 08:20 UTC, merged